### PR TITLE
fix (build_validation) Incorrect field paths returned

### LINKED ISSUE #484: incorrect paths in webhook validation failures
Found a bug in Build's webhook:
```
2018/11/30 19:33:05 Unexpected error: Internal error occurred: admission webhook "webhook.build.knative.dev" denied the request: mutation failed: missing field(s): spec.b.spec.template
missing field(s): spec.b.spec.steps
```

that field path is clearly wrong

I see those coming from here:
https://github.com/knative/build/blob/92d2bf3eee363ee915cbe1c2d65b2d8526314afc/pkg/apis/build/v1alpha1/build_validation.go#L37

### PR DESCRIPTION
**Pull request by prithviramesh**
This pr _attempts_ to fix #484

## Proposed Changes

*if a user tries to create a `Build` with a `BuildSpec` that has both `Template` and `Steps` return `ErrDisallowedFields(b.spec.steps)` because a `BuildTemplate` already includes `Steps` for the `Build` through its `BuildTemplateSpec`:

https://github.com/knative/build/blob/47e45d6af31266829e0eb362f0f250e70e041a63/pkg/apis/build/v1alpha1/build_template_types.go#L69

### CODE REVIEW

File: pkg/apis/build/v1alpha1/build_validation.go [hunk 1]
```diff
@@ -34,7 +34,7 @@ func (bs *BuildSpec) Validate() *apis.FieldError {
 		return apis.ErrMissingField("b.spec.template").Also(apis.ErrMissingField("b.spec.steps"))
 	}
 	if bs.Template != nil && len(bs.Steps) > 0 {
-		return apis.ErrMissingField("b.spec.template").Also(apis.ErrMissingField("b.spec.steps"))
+		return apis.ErrDisallowedFields("b.spec.steps")
```
[the remark this answers is not in the document]
Comment (prithviramesh) [reply pkg/apis/build/v1alpha1/build_validation.go]: Thanks for pointing me in the right direction, I went ahead and pushed up a commit with this change.

**Comment by mattmoor** [comment]
@prithviramesh yes that's right.  You can explore how we use this in serving here: https://github.com/knative/serving/blob/master/pkg/apis/serving/v1alpha1/configuration_validation_test.go

**Comment by prithviramesh** [comment]
@mattmoor I went through `build_validation.go` and _attempted_ to fix all the field paths with relevant/corrected Error types. I also added some comments around removing redundant code, and a *potential* bug I think I found in one of the validate() methods.

I will work on the next iteration pending your review, thanks in advance!

**Comment by prithviramesh** [comment]
Also: I see the same erroneous field path naming conventions i.e `b.spec.template.kind` in other files. I want to fix those as well, should I include those changes as part of this PR or open a separate PR to fix the field paths outside of `build_validation`?

**Comment by mattmoor** [comment]
I'm happy to see it all fixed in one go if you are up for it.

File: pkg/apis/build/v1alpha1/build_validation.go [hunk 2]
```diff
@@ -68,15 +73,15 @@ func (b *TemplateInstantiationSpec) Validate() *apis.FieldError {
 		return nil
 	}
 	if b.Name == "" {
-		return apis.ErrMissingField("build.spec.template.name")
+		return apis.ErrMissingField("name").ViaField("template")
```
Comment (mattmoor) [inline pkg/apis/build/v1alpha1/build_validation.go]: The `.ViaField` should be in the caller (we don't know what field this was accessed through.

File: pkg/apis/build/v1alpha1/build_validation.go [hunk 3]
```diff
@@ -90,9 +95,9 @@ func (bt *BuildSpec) validateTimeout() *apis.FieldError {
 	maxTimeout := time.Duration(24 * time.Hour)
 
 	if bt.Timeout.Duration > maxTimeout {
-		return apis.ErrInvalidValue(fmt.Sprintf("%s should be < 24h", bt.Timeout), "b.spec.timeout")
+		return apis.ErrInvalidValue(fmt.Sprintf("%s should be < 24h", bt.Timeout), "timeout")
 	} else if bt.Timeout.Duration < 0 {
-		return apis.ErrInvalidValue(fmt.Sprintf("%s should be > 0", bt.Timeout), "b.spec.timeout")
+		return apis.ErrInvalidValue(fmt.Sprintf("%s should be > 0", bt.Timeout), "timeout")
```
Comment (mattmoor) [inline pkg/apis/build/v1alpha1/build_validation.go]: There is a helper that @k4leung4 added for erroring on a bounded value like this.

File: pkg/apis/build/v1alpha1/build_validation.go [hunk 4]
```diff
@@ -31,16 +31,21 @@ func (b *Build) Validate() *apis.FieldError {
...
-		apis.ErrMissingField("build.spec.template.name")
-	}
+		apis.ErrMissingField("name").ViaField("template")
+	}*/
 
+
+	/*below method potentially has a bug:
+		it does not Validate if only a "Source" has been set, it only validates if multiple sources have been set
+	*/
 	if err := bs.validateSources(); err != nil {
```
Comment (mattmoor) [inline pkg/apis/build/v1alpha1/build_validation.go]: For many of the following checks, we can actually group them all up with `.Also()`, which is designed to handle nil, so you don't need a giant chain of `nil` checks.

File: pkg/apis/build/v1alpha1/build_validation.go (hunk 2 above)
Comment (prithviramesh) [reply pkg/apis/build/v1alpha1/build_validation.go]: I can see how the best pattern to follow for `ViaField()` is to add it to the caller, mainly because of the reason you put, but for the sake of learning: could `Validate` implemented as part of an TemplateInstantiationSpec interface ever not be called by the `template` field?

That being asked, I will definitely go ahead and move the `ViaField()` to the caller.

File: pkg/apis/build/v1alpha1/build_validation.go (hunk 3 above)
Comment (prithviramesh) [reply pkg/apis/build/v1alpha1/build_validation.go]: I'll go comb through the code for it, thanks for the heads up

File: pkg/apis/build/v1alpha1/build_validation.go (hunk 4 above)
Comment (prithviramesh) [reply pkg/apis/build/v1alpha1/build_validation.go]: Again, thanks for the heads up; That definitely sounds like a cleaner way to implement this part!

File: pkg/apis/build/v1alpha1/build_validation.go (hunk 3 above)
Comment (prithviramesh) [reply pkg/apis/build/v1alpha1/build_validation.go]: I found the method:
https://github.com/knative/pkg/blob/0e41760cea1d1ce16f4cc311c2d6bd3525bb3da7/apis/field_error.go#L341

The one thing I'm seeing is that the `ErrOutOfBoundsValue` method does not exist in the version of `field_error.go` that's contained in my fork's vendored dependencies. Should I upgrade the dependency version?

File: pkg/apis/build/v1alpha1/build_validation.go [hunk 5]
```diff
@@ -31,34 +31,40 @@ func (b *Build) Validate() *apis.FieldError {
...
-	if err := ValidateVolumes(bs.Volumes); err != nil {
-		return err
+		return bs.Template.Validate().ViaField("template")
 	}
-	if err := bs.validateTimeout(); err != nil {
+
+	/*below method potentially has a bug:
+	it does not Validate if only a "Source" has been set, it only validates if multiple sources have been set
+	*/
+	if err := bs.validateSources().Also(ValidateVolumes(bs.Volumes)).Also(bs.validateTimeout()).Also(validateSteps(bs.Steps)); err != nil {
```
Comment (mattmoor) [inline pkg/apis/build/v1alpha1/build_validation.go]: We don't even need the `nil` check, we can now just right:
```go
return bs.validateSources().
    Also(ValidateVolumes(bs.Volumes)).
    Also(bs.validateTimeout()).
    Also(validateSteps(bs.Steps))
```

File: pkg/apis/build/v1alpha1/build_validation.go [hunk 6]
```diff
@@ -31,34 +31,40 @@ func (b *Build) Validate() *apis.FieldError {
...
-	}
-	if err := ValidateVolumes(bs.Volumes); err != nil {
-		return err
+		return bs.Template.Validate().ViaField("template")
 	}
-	if err := bs.validateTimeout(); err != nil {
+
+	/*below method potentially has a bug:
+	it does not Validate if only a "Source" has been set, it only validates if multiple sources have been set
+	*/
```
Comment (mattmoor) [inline pkg/apis/build/v1alpha1/build_validation.go]: nit: prefer `//`-style comments

/lint

File: pkg/apis/build/v1alpha1/build_validation.go [hunk 7]
```diff
@@ -108,18 +114,17 @@ func (bs BuildSpec) validateSources() *apis.FieldError {
...
 	if len(bs.Sources) > 0 && bs.Source != nil {
-		return apis.ErrMultipleOneOf("b.spec.source", "b.spec.sources")
+		return apis.ErrMultipleOneOf("source", "sources")
 	}
-
 	for _, source := range bs.Sources {
 		// check all source have unique names
 		if _, ok := names[source.Name]; ok {
-			return apis.ErrMultipleOneOf("b.spec.sources.names")
+			return apis.ErrInvalidKeyName("SourceName", "name", "Duplicate Found").ViaField("source").ViaField("sources")
```
Comment (mattmoor) [inline pkg/apis/build/v1alpha1/build_validation.go]: I think `MultipleOneOf` was likely right here before

File: pkg/apis/build/v1alpha1/build_validation.go (hunk 3 above)
Comment (mattmoor) [reply pkg/apis/build/v1alpha1/build_validation.go]: Yeah, you should just have to update the commit in `Gopkg.toml` and run `./hack/update-deps.sh`.

**Comment by prithviramesh** [comment]
@mattmoor I'll go ahead and append to `build_validation_test.go` to validate the expected field paths from the errors; Currently the tests pass as long as an error is returned and the test is expecting some error:
```
        verr := c.build.Validate()
        if gotErr, wantErr := verr != nil, c.reason != ""; gotErr != wantErr {
		t.Errorf("validateBuild(%s); got %#v, want %q", name, verr, c.reason)
	}
```

File: pkg/apis/build/v1alpha1/build_validation.go [hunk 8]
```diff
@@ -130,12 +123,12 @@ func (bs BuildSpec) validateSources() *apis.FieldError {
...
 			}
 			if emptyTargetPath {
-				return apis.ErrInvalidValue("empty target path", "b.spec.sources.targetPath")
+				return apis.ErrInvalidValue("Empty Target Path", "targetPath").ViaField("source").ViaField("sources")
 			}
 			emptyTargetPath = true
 		} else {
 			if source.Custom != nil {
-				return apis.ErrInvalidValue(source.TargetPath, "b.spec.sources.targetPath")
+				return apis.ErrInvalidValue(source.TargetPath, "targetPath").ViaField("source").ViaField("sources")
```
[the remark this answers is not in the document]
Comment (prithviramesh) [reply pkg/apis/build/v1alpha1/build_validation.go]: No I did not, thanks for catching this.

**Comment by prithviramesh** [comment]
@mattmoor I fixed a couple more fieldpaths and pushed up a redone version of `build_validation_test.go` that follows the testing pattern in `knative/serving` and verifies the FieldErrors received against expected values.

screen shot 2018-12-10 at 10 42 59 pm
I ran the updated tests in `build_validation_test.go` against all of my changes in this PR and they seem to have passed successfully.

**Comment by shashwathi** [comment]
@prithviramesh : Check the logs of failed test (open the`skipping lines` part of logs )
```
I1220 23:19:00.874]  [[projects]]
I1220 23:19:00.874] -  digest = "1:9d8420bbf131d1618bde6530af37c3799340d3762cc47210c1d9532a4c3a2779"
I1220 23:19:00.874] +  digest = "1:e3707aeaccd2adc89eba6c062fec72116fe1fc1ba71097da85b4d8ae1668a675"
I1220 23:19:00.874]    name = "github.com/spf13/pflag"
I1220 23:19:00.874]    packages = ["."]
I1220 23:19:00.874]    pruneopts = "NUT"
I1220 23:19:01.289] /go/src/github.com/knative/build is out of date. Please run hack/update-codegen.sh
```

This is why tests are failing. Looks like there is a mismatch of dependent library in this PR. Run the script `hack/update-codegen.sh` and update the PR please.

**Comment by prithviramesh** [comment]
@shashwathi that did the trick, I was focused on the wrong log line.
