### PR TITLE
Controller test

### LINKED ISSUE #265: Bring up code coverage of controller to 80%
/area test-and-release
/kind doc

Expected Behavior
github.com/knative/build/pkg/controller code cover should be 80+%

Actual Behavior
It's at 50.5%.

Steps to Reproduce the Problem
Pls refer to https://testgrid-dot-knative-tests.appspot.com/knative-build#coverage for up-to-date CC numbers

Additional Info

### PR DESCRIPTION
**Pull request by shashwathi**
Fixes #265 

## Proposed Changes

  * Add tests for build controller
  * Update error msg when cluster build template/ build template is not found 
  * Add hooks in nop builder for inducing error scenarios 

/assign @ImJasonH 
/assign @pivotal-nader-ziada

### CODE REVIEW

File: pkg/builder/nop/builder.go [hunk 1]
```diff
@@ -59,6 +59,9 @@ func (nb *operation) Checkpoint(_ *v1alpha1.Build, status *v1alpha1.BuildStatus)
 }
 
 func (nb *operation) Terminate() error {
+	if nb.builder.OpErr != nil {
```
Comment (ImJasonH) [inline pkg/builder/nop/builder.go]: You can just return `nb.builder.OpErr` here.

File: pkg/controller/build/controller_test.go [hunk 2]
```diff
@@ -299,3 +523,99 @@ func TestTimeoutFlows(t *testing.T) {
...
+	}
+
+	// Update status to past time by substracting buffer time
+	first.Status.CreationTime.Time = metav1.Now().Time.Add(-buffer)
+
+	// We have to manually update the index, or the controller won't see the update.
+	f.updateIndex(i, []*v1alpha1.Build{first})
+
+	// Run a second iteration of the syncHandler to receive error from operation.
+	if err := c.syncHandler(getKey(build, t)); err == nil || cmp.Diff(err.Error(), oppErr.Error()) != "" {
```
Comment (ImJasonH) [inline pkg/controller/build/controller_test.go]: This could just check `err != opErr`

**Comment by shashwathi** [comment]
/hold

There is data race. Let me fix that

**Comment by shashwathi** [comment]
@ImJasonH : Addressed your comments

File: pkg/builder/nop/builder_test.go [hunk 3]
```diff
@@ -137,3 +139,20 @@ func TestOperationFromStatus(t *testing.T) {
 		t.Errorf("ErrorMessage(%v); wanted not failed, got %q", status, msg)
 	}
 }
+
+func TestTerminate(t *testing.T) {
+	builder := Builder{
+		OpErr: errors.New("testerr"),
+	}
+	op, err := builder.OperationFromStatus(&v1alpha1.BuildStatus{
+		Google: &v1alpha1.GoogleSpec{
```
Comment (pivotal-nader-ziada) [inline pkg/builder/nop/builder_test.go]: Might be out of the scope of this PR, but we should rename GoogleSpec since we don't have google builder anymore

Comment (shashwathi) [reply pkg/builder/nop/builder_test.go]: @ImJasonH mentioned in earlier comment that about cleaning this up in v1alpha2

Comment (ImJasonH) [reply pkg/builder/nop/builder_test.go]: The only thing that uses `GoogleSpec` anymore is the nop builder, and I think as an aspiration I'd like it'd be cool to see if we can get rid of nop builder too, and just use a cluster builder implementation backed by fake k8s clients.

But yeah, as for dropping `GoogleSpec` I think we have to wait until v1alpha2 to make breaking changes, and CRD versioning won't have a good story for a couple more k8s releases it looks like :(

File: pkg/controller/build/controller_test.go [hunk 4]
```diff
@@ -18,18 +18,27 @@ package build
 
 import (
 	"errors"
+	"fmt"
 	"strings"
 	"testing"
 	"time"
 
+	"github.com/google/go-cmp/cmp"
```
Comment (ImJasonH) [inline pkg/controller/build/controller_test.go]: nit: I try to keep imports somewhat tidy, in just three blocks: go stdlib imports, non-`knative/build` imports, and then `knative/build` imports. The second block includes packages from `knative/pkg`, since those are vendored and aren't under our direct control in this repo.

File: pkg/controller/build/controller_test.go [hunk 5]
```diff
@@ -95,12 +100,203 @@ func (f *fixture) updateIndex(i informers.SharedInformerFactory, bl []*v1alpha1.
...
+	defer close(stopCh)
+	defer close(eventCh)
+
+	c, i, k8sI := f.newController(bldr, eventCh)
+	f.updateIndex(i, []*v1alpha1.Build{build})
+	i.Start(stopCh)
+	k8sI.Start(stopCh)
+
+	// induce failure when fetching build information in controller
+	reactor := func(action clientgotesting.Action) (handled bool, ret runtime.Object, err error) {
```
Comment (ImJasonH) [inline pkg/controller/build/controller_test.go]: Ooooh fancy, I like this a lot :+1:

File: pkg/controller/build/controller_test.go [hunk 6]
```diff
@@ -95,12 +100,203 @@ func (f *fixture) updateIndex(i informers.SharedInformerFactory, bl []*v1alpha1.
...
+	k8sI.Start(stopCh)
+
+	if err := c.syncHandler(getKey(build, t)); err != nil {
+		t.Errorf("Unexpected error while syncing build: %s", err.Error())
+	}
+}
+
+func TestBuildWithNonExistentTemplates(t *testing.T) {
+	tests := []struct {
+		bldr  builder.Interface
```
Comment (ImJasonH) [inline pkg/controller/build/controller_test.go]: `bldr` is only passed as `&nop.Builder{}`, so it doesn't need to be a field in the test case struct.

In fact, the only thing that varies between the two `build`s is the `Kind`, so maybe just make that the test case:

```
for _, kind := []string{BuildTemplateKind, ClusterBuildTemplateKind} {
  ...
}
```

File: pkg/controller/build/controller_test.go [hunk 7]
```diff
@@ -95,12 +100,203 @@ func (f *fixture) updateIndex(i informers.SharedInformerFactory, bl []*v1alpha1.
...
+		eventCh := make(chan string, 1024)
+		defer close(stopCh)
+		defer close(eventCh)
+
+		c, i, k8sI := f.newController(test.bldr, eventCh)
+		f.updateIndex(i, []*v1alpha1.Build{test.build()})
+		i.Start(stopCh)
+		k8sI.Start(stopCh)
+
+		err := c.syncHandler(getKey(test.build(), t))
```
Comment (ImJasonH) [inline pkg/controller/build/controller_test.go]: nit: `if err := ...; err == nil { ... } else if !kuberrors.IsNotFound(err) { ... }`

File: pkg/controller/build/controller_test.go [hunk 8]
```diff
@@ -95,12 +100,203 @@ func (f *fixture) updateIndex(i informers.SharedInformerFactory, bl []*v1alpha1.
...
+		if err == nil {
+			t.Errorf("Expect error syncing build")
+		}
+		if !kuberrors.IsNotFound(err) {
+			t.Errorf("Expect error to be not found err: %s", err.Error())
+		}
+	}
+}
+
+func TestBuilWithTemplate(t *testing.T) {
```
Comment (ImJasonH) [inline pkg/controller/build/controller_test.go]: typo: `TestBuildWithTemplate`

File: pkg/controller/build/controller_test.go (hunk 4 above)
Comment (shashwathi) [reply pkg/controller/build/controller_test.go]: Okay I like that approach. I think on Vscode Go plugin re-arranges the imports so I have to manually check it didn't override my arrangement 👍

File: pkg/controller/build/controller_test.go (hunk 7 above)
Comment (shashwathi) [reply pkg/controller/build/controller_test.go]: I will consider writing a git commit hook to catch this in future :D
